---
abstract: 'Create simple (command line) applications'
author:
  - 'Jakob Voß <voss@gbv.de>'
build_requires:
  Config::Tiny: 0
  Data::Dumper: 0
  File::Temp: 0
  Test::More: 0
  perl: v5.10.1
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Run
requires:
  Carp: 0
  Clone: 0
  Config::Any: 0
  File::Basename: 0
  Getopt::Long: 0
  Log::Contextual: 0
  Log::Contextual::WarnLogger: 0
  Log::Log4perl: 0
  Pod::Usage: 0
  Scalar::Util: 0
  Try::Tiny: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/nichtich/App-Run/issues
  homepage: https://github.com/nichtich/App-Run
  repository: https://github.com/nichtich/App-Run.git
version: 0.02
